# Generated by Django 4.2 on 2026-02-22 21:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
